min_version = "2024.9.5"

[env]
# Use the project name derived from the current directory
PROJECT_NAME = "{{ config_root | basename }}"

# Automatic virtualenv activation
_.python.venv = { path = ".venv", create = true }

[tools]
python = "{{ get_env(name='PYTHON_VERSION', default='3.13') }}"
uv = "latest"

[tasks.install]
description = "Install dependencies"
alias = "i"
run = "uv sync"

[tasks.info]
description = "Print project information"
run = '''
echo "Project: $PROJECT_NAME"
echo "Virtual Environment: $VIRTUAL_ENV"
'''

[tasks.landcover_notebook]
description = "View landcover notebook"
run = "jupyter notebook notebooks/landcover.ipynb"

[tasks.landcover_notebook_trust]
description = "Trust landcover notebook"
run = "jupyter trust notebooks/landcover.ipynb"

[tasks.evapo_notebook]
description = "View evapotranspiration notebook"
run = "jupyter notebook notebooks/evapotranspiration.ipynb"

[tasks.evapo_notebook_trust]
description = "Trust evapotranspiration notebook"
run = "jupyter trust notebooks/evapotranspiration.ipynb"
